[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"
  
[build.environment]
  HUGO_VERSION = "0.70.0"
  HUGO_THEME = "repo"
